streamlit.header( 'Breakfast Favorites")
streamlit.text(' Omega 3 & Blueberry Oatmeal') 
streamlit. text ('03 Kale, Spinach & Rocket Smoothie') 
streamlit.text ('« Hard-Boiled Free-Range Egg')
streamlit.text('Avocado Toast')
